import 'roboto-fontface/css/roboto/roboto-fontface.css';
export declare const globalClass: string;
export declare const containerClass: string;
export declare const diagramClass: string;
export declare const viewportClass: string;
export declare const CellularComponentClass: string;
export declare const DataNodeClass: string;
export declare const LabelClass: string;
export declare const StateClass: string;
export declare const GroupGroupClass: string;
export declare const GroupComplexClass: string;
export declare const GroupNoneClass: string;
export declare const GroupPathwayClass: string;
export declare const InteractionClass: string;
export declare const InhibitionClass: string;
export declare const CitationClass: string;
export declare const InfoBoxClass: string;
